(use-package ligature
  :straight t
  :config
  (ligature-set-ligatures 'prog-mode '("<---" "<--"  "<<-" "<-" "->" "-->" "--->" "<->" "<-->" "<--->" "<---->" "<!--"
                                       "<==" "<===" "<=" "=>" "=>>" "==>" "===>" ">=" "<=>" "<==>" "<===>" "<====>" "<!---"
                                       "<~~" "<~" "~>" "~~>" "::" ":::" "==" "!=" "===" "!=="
                                       ":=" ":-" ":+" "<*" "<*>" "*>" "<|" "<|>" "|>" "+:" "-:" "=:" "<******>" "++" "+++"))
  (global-ligature-mode t))

;; Dyalog APL characters
(define-key key-translation-map (kbd "C-` ~") "⌺")
(define-key key-translation-map (kbd "C-` !") "⌶")
(define-key key-translation-map (kbd "C-` @") "⍫")
(define-key key-translation-map (kbd "C-` #") "⍒")
(define-key key-translation-map (kbd "C-` $") "⍋")
(define-key key-translation-map (kbd "C-` %") "⌽")
(define-key key-translation-map (kbd "C-` ^") "⍉")
(define-key key-translation-map (kbd "C-` &") "⊖")
(define-key key-translation-map (kbd "C-` *") "⍟")
(define-key key-translation-map (kbd "C-` (") "⍱")
(define-key key-translation-map (kbd "C-` )") "⍲")
(define-key key-translation-map (kbd "C-` _") "!")
(define-key key-translation-map (kbd "C-` +") "⌹")
(define-key key-translation-map (kbd "C-` `") "⋄")
(define-key key-translation-map (kbd "C-` 1") "¨")
(define-key key-translation-map (kbd "C-` 2") "¯")
(define-key key-translation-map (kbd "C-` 3") "<")
(define-key key-translation-map (kbd "C-` 4") "≤")
(define-key key-translation-map (kbd "C-` 5") "=")
(define-key key-translation-map (kbd "C-` 6") "≥")
(define-key key-translation-map (kbd "C-` 7") ">")
(define-key key-translation-map (kbd "C-` 8") "≠")
(define-key key-translation-map (kbd "C-` 9") "∨")
(define-key key-translation-map (kbd "C-` 0") "∧")
(define-key key-translation-map (kbd "C-` -") "×")
(define-key key-translation-map (kbd "C-` =") "÷")
(define-key key-translation-map (kbd "C-` E") "⍷")
(define-key key-translation-map (kbd "C-` T") "⍨")
(define-key key-translation-map (kbd "C-` I") "⍸")
(define-key key-translation-map (kbd "C-` O") "⍥")
(define-key key-translation-map (kbd "C-` P") "⍣")
(define-key key-translation-map (kbd "C-` {") "⍞")
(define-key key-translation-map (kbd "C-` }") "⍬")
(define-key key-translation-map (kbd "C-` |") "⊣")
(define-key key-translation-map (kbd "C-` q") "?")
(define-key key-translation-map (kbd "C-` w") "⍵")
(define-key key-translation-map (kbd "C-` e") "∊")
(define-key key-translation-map (kbd "C-` r") "⍴")
(define-key key-translation-map (kbd "C-` t") "~")
(define-key key-translation-map (kbd "C-` y") "↑")
(define-key key-translation-map (kbd "C-` u") "↓")
(define-key key-translation-map (kbd "C-` i") "⍳")
(define-key key-translation-map (kbd "C-` o") "○")
(define-key key-translation-map (kbd "C-` p") "*")
(define-key key-translation-map (kbd "C-` [") "←")
(define-key key-translation-map (kbd "C-` ]") "→")
(define-key key-translation-map (kbd "C-` \\") "⊢")
(define-key key-translation-map (kbd "C-` J") "⍤")
(define-key key-translation-map (kbd "C-` K") "⌸")
(define-key key-translation-map (kbd "C-` L") "⌷")
(define-key key-translation-map (kbd "C-` :") "≡")
(define-key key-translation-map (kbd "C-` \"") "≢")
(define-key key-translation-map (kbd "C-` a") "⍺")
(define-key key-translation-map (kbd "C-` s") "⌈")
(define-key key-translation-map (kbd "C-` d") "⌊")
(define-key key-translation-map (kbd "C-` f") "_")
(define-key key-translation-map (kbd "C-` g") "∇")
(define-key key-translation-map (kbd "C-` h") "∆")
(define-key key-translation-map (kbd "C-` j") "∘")
(define-key key-translation-map (kbd "C-` k") "'")
(define-key key-translation-map (kbd "C-` l") "⎕")
(define-key key-translation-map (kbd "C-` ;") "⍎")
(define-key key-translation-map (kbd "C-` '") "⍕")
(define-key key-translation-map (kbd "C-` Z") "⊆")
(define-key key-translation-map (kbd "C-` <") "⍪")
(define-key key-translation-map (kbd "C-` >") "⍙")
(define-key key-translation-map (kbd "C-` ?") "⍠")
(define-key key-translation-map (kbd "C-` z") "⊂")
(define-key key-translation-map (kbd "C-` x") "⊃")
(define-key key-translation-map (kbd "C-` c") "∩")
(define-key key-translation-map (kbd "C-` v") "∪")
(define-key key-translation-map (kbd "C-` b") "⊥")
(define-key key-translation-map (kbd "C-` n") "⊤")
(define-key key-translation-map (kbd "C-` m") "|")
(define-key key-translation-map (kbd "C-` ,") "⍝")
(define-key key-translation-map (kbd "C-` .") "⍀")
(define-key key-translation-map (kbd "C-` /") "⌿")


(provide 'ligatures)
